# Generated by Django 5.1 on 2024-08-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CityWeather",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=250)),
                ("temp_c", models.FloatField()),
                ("temp_f", models.FloatField()),
                ("humidity", models.FloatField()),
                ("date", models.DateTimeField()),
                ("country", models.CharField(max_length=250)),
            ],
        ),
    ]
