# Generated by Django 5.1 on 2024-08-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CityWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=250)),
                ("temp_c", models.FloatField()),
                ("temp_f", models.FloatField()),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
